name: CI and Deployment

on:

  push:

    branches: [ develop ]

  pull_request:

    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Run actions

        uses: actions/setup-node@v2


  deploy:

    needs: [build]

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2


      - name: Copy file to server

        uses: appleboy/scp-action@v0.1.4

        with:

          host: ${{ secrets.SERVER_IP }}

          username: ${{ secrets.SERVER_USERNAME }}

          password: ${{ secrets.PASSWORD }}

          port: 22

          key: ${{ secrets.DEPLOY_KEY }}

          source: "./"

          target: "~/nuxt-express"

 
      - name: Run build

        uses: appleboy/ssh-action@master

        with:

          host: ${{ secrets.SERVER_IP }}

          username: ${{ secrets.SERVER_USERNAME }}

          key: ${{ secrets.DEPLOY_KEY }}

          port: 22

          script:

            chown -R root ~/nuxt-express && cd ~/nuxt-express && pm2 stop 0 && npm install && npm run build && pm2 start npm -- start